CREATE TABLE BIKETYPES_CH (
    BIKE_TYPE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    DESCRIPTION CLOB
);

CREATE SEQUENCE BIKE_TYPE_ID_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE USERS_BIKE (
    USER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    CPF VARCHAR2(14) UNIQUE NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE SEQUENCE USER_ID_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE BIKES_CH (
    BIKE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER,
    BIKE_TYPE_ID NUMBER,
    BRAND VARCHAR2(50) NOT NULL,
    SERIAL_NUMBER VARCHAR2(50) NOT NULL,
    YEAR NUMBER NOT NULL,
    VALUE NUMBER NOT NULL,
    ADDITIONAL_MODIFICATIONS CLOB,
    FOREIGN KEY (USER_ID) REFERENCES USERS_BIKE(USER_ID),
    FOREIGN KEY (BIKE_TYPE_ID) REFERENCES BIKETYPES_CH(BIKE_TYPE_ID)
);

CREATE SEQUENCE BIKE_ID_SEQ START WITH 1 INCREMENT BY 1;